server:
  port: 8085

spring:
  profiles:
    active: at-least-once,at-most-once,exactly-once,outbox,topic-creation
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.web: DEBUG

kafka:
  topic:
    partitions: 3
    replication-factor: 3
    atleastonce:
      name: at-least-once-topic
    atmostonce:
      name: at-most-once-topic
    exactlyonce:
      name: exactly-once-topic
    transactiontopic:
      check-transaction-topic